FROM rust:1.82-bullseye

# Install rustfmt
RUN rustup component add rustfmt

# Fetch packages and upgrade
RUN apt update -y && apt upgrade -y

# Install zsh sudo, and nano
RUN apt install zsh sudo nano -y

# Set it to the default shell
RUN sudo chsh -s $(which zsh)

# Install OhMyZSH
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install starship
RUN curl -sS https://starship.rs/install.sh | sh -s -- -y

# Make starship the default prompt
WORKDIR /home/ritangle
RUN echo 'eval "$(starship init zsh)"' >> $HOME/.zshrc

# Install starship config
COPY starship.toml /home/ritangle/.config/starship.toml